title: "Prabhav Singh"
url:   "https://prabhav55221.github.io"
baseurl: ""

owner:
  name:    "Prabhav Singh"
  email:   "psingh54@jhu.edu"
  twitter: "psingh522"
  github:  "Prabhav55221"

collections:
  notes:
    output: true
    permalink: /notes/:name/
  reading_notes:
    output: true
    permalink: /reading-notes/:name/

defaults:
  - scope:
      path: ""
      type: "notes"
    values:
      layout: "notes"
  - scope:
      path: ""
      type: "reading_notes"
    values:
      layout: "reading-note"

markdown:    kramdown
highlighter: rouge

kramdown:
  math_engine: none
  input: GFM
  hard_wrap: false

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - backup
  - "*.sh"
